### ISSUE TITLE
Evaluation Error

### ISSUE THREAD

**Issue by changliucoding** [exiawsh/StreamPETR#51]
Hi,
I'm trying to reproduce your great project. I want to get the result first on Mini dataset. So here is what I did.
I followed the environment setup and data preparation steps. Instead of downloading the full-dataset, I replaced them with mini dataset. so here is what my data folder looks like:
![Screenshot from 2023-07-09 16-10-31](https://github.com/exiawsh/StreamPETR/assets/133587429/0296a0de-33ca-49fa-b751-1c516749a010)
I didn't generate the pkl file myself, I found you uploaded mini pkl before, so I downloaded them and renamed them to nuscenes2d_temporal_infos_train.pkl and nuscenes2d_temporal_infos_val.pkl.

Then I went to the third step and want to do the Evaluation:
tools/dist_test.sh projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py work_dirs/stream_petr_vov_flash_800_bs2_seq_24e/latest.pth 8 --eval bbox

Since work_dirs/stream_petr_vov_flash_800_bs2_seq_24e/latest.pth is the path for checkpoint so I renamed it to ckpts/stream_petr_vov_flash_800_bs2_seq_24e.pth

And I am using an one gpu 4060 8GB laptop, so I switched 8 to 1. So my running command for Evaluation is : 
tools/dist_test.sh projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py ckpts/stream_petr_vov_flash_800_bs2_seq_24e.pth 1 --eval bbox

Then running it I got error : 
RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)`

I wonder which step I am missing? I saw that you said in previous issue that a laptop with a gpu that has higher than 6GB could run it. So I want to reproduce your work, I am looking forward to hearing from you, thanks!

**Comment by changliucoding** [comment]
The following is the whole error info from terminal:

./tools/dist_test.sh projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py ckpts/stream_petr_vov_flash_800_bs2_seq_24e.pth 1 --format-only
/home/chang/anaconda3/envs/streampetr/lib/python3.8/site-packages/torch/distributed/launch.py:163: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn(
The module torch.distributed.launch is deprecated and going to be removed in future.Migrate to torch.distributed.run
INFO:torch.distributed.launcher.api:Starting elastic_operator with launch configs:
  entrypoint       : ./tools/test.py
  min_nodes        : 1
  max_nodes        : 1
  nproc_per_node   : 1
  run_id           : none
  rdzv_backend     : static
  rdzv_endpoint    : 127.0.0.1:29500
  rdzv_configs     : {'rank': 0, 'timeout': 900}
  max_restarts     : 3
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

INFO:torch.distributed.elastic.agent.server.local_elastic_agent:log directory set to: /tmp/torchelastic_b3p94eyw/none_19w_4r39
INFO:torch.distributed.elastic.agent.server.api:[default] starting workers for entrypoint: python
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
/home/chang/anaconda3/envs/streampetr/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py:52: FutureWarning: This is an experimental API and will be changed in future.
  warnings.warn(
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_b3p94eyw/none_19w_4r39/attempt_0/0/error.json
projects.mmdet3d_plugin
load checkpoint from local path: ckpts/stream_petr_vov_flash_800_bs2_seq_24e.pth
[                                                  ] 0/81, elapsed: 0s, ETA:/home/chang/anaconda3/envs/streampetr/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
  File "./tools/test.py", line 262, in <module>
    main()
  File "./tools/test.py", line 232, in main
    outputs = custom_multi_gpu_test(model, data_loader, args.tmpdir,
  File "/home/chang/Desktop/Git/github/StreamPETR/projects/mmdet3d_plugin/core/apis/test.py", line 72, in custom_multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/chang/anaconda3/envs/streampetr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chang/anaconda3/envs/streampetr/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/chang/anaconda3/envs/streampetr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chang/anaconda3/envs/streampetr/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 205, in new_func
    return old_func(*args, **kwargs)
  File "/home/chang/Desktop/Git/github/StreamPETR/projects/mmdet3d_plugin/models/detectors/petr3d.py", line 218, in forward
    return self.forward_test(**data)
  File "/home/chang/Desktop/Git/github/StreamPETR/projects/mmdet3d_plugin/models/detectors/petr3d.py", line 285, in forward_test
    return self.simple_test(img_metas[0], **data)
  File "/home/chang/Desktop/Git/github/StreamPETR/projects/mmdet3d_plugin/models/detectors/petr3d.py", line 314, in simple_test
    bbox_pts = self.simple_test_pts(
  File "/home/chang/Desktop/Git/github/StreamPETR/projects/mmdet3d_plugin/models/detectors/petr3d.py", line 300, in simple_test_pts
    outs = self.pts_bbox_head(location, img_metas, topk_indexes, **data)
  File "/home/chang/anaconda3/envs/streampetr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chang/Desktop/Git/github/StreamPETR/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py", line 589, in forward
    pos_embed, cone = self.position_embeding(data, memory_center, topk_indexes, img_metas)
  File "/home/chang/Desktop/Git/github/StreamPETR/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py", line 403, in position_embeding
    img2lidars = data['lidar2img'].inverse()
RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)`
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 21637) of binary: /home/chang/anaconda3/envs/streampetr/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_b3p94eyw/none_19w_4r39/attempt_1/0/error.json
projects.mmdet3d_plugin

**Comment by exiawsh** [comment]
@changliucoding  It seems that pytorch has some bug in the 4060 8GB laptop when conducting inverse operation. 
Try to change this line to 
img2lidars = np.linalg.inv(data['lidar2img'].cpu().numpy())
img2lidars = torch.tensor(img2lidars, device=data[intrinsics].device())
https://github.com/exiawsh/StreamPETR/blob/1111ff(aa685068059fb112e58c6c4bb9d9c418f6/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py#L403

**Comment by changliucoding** [comment]
> img2lidars = np.linalg.inv(data['lidar2img'].cpu().numpy())

Hi your link is not valid to me. 
Do you mean I changed
        img2lidars = data['lidar2img'].inverse()
        img2lidars = img2lidars.view(BN, 1, 1, 4, 4).repeat(1, H*W, D, 1, 1).view(B, LEN, D, 4, 4)
        img2lidars = topk_gather(img2lidars, topk_indexes)
to 
img2lidars = np.linalg.inv(data['lidar2img'].cpu().numpy())
img2lidars = torch.tensor(img2lidars, device=data[intrinsics].device())
?

**Comment by exiawsh** [comment]
@changliucoding 
Hi your link is not valid to me.
Do you mean I changed
img2lidars = data['lidar2img'].inverse()
img2lidars = img2lidars.view(BN, 1, 1, 4, 4).repeat(1, H*W, D, 1, 1).view(B, LEN, D, 4, 4)
img2lidars = topk_gather(img2lidars, topk_indexes)
to
img2lidars = np.linalg.inv(data['lidar2img'].cpu().numpy())
img2lidars = torch.tensor(img2lidars, device=data[intrinsics].device())
img2lidars = img2lidars.view(BN, 1, 1, 4, 4).repeat(1, H*W, D, 1, 1).view(B, LEN, D, 4, 4)
img2lidars = topk_gather(img2lidars, topk_indexes)

**Comment by changliucoding** [comment]
> s

Hi! Thanks I think maybe above has some typos,and i wrote them like:

        img2lidars = np.linalg.inv(data['lidar2img'].cpu().numpy())
        img2lidars = torch.tensor(img2lidars, device=data[intrinsic].device())
        img2lidars = img2lidars.view(BN, 1, 1, 4, 4).repeat(1, H*W, D, 1, 1).view(B, LEN, D, 4, 4)
        img2lidars = topk_gather(img2lidars, topk_indexes)

But then I met another issue when running it:

load checkpoint from local path: ckpts/stream_petr_vov_flash_800_bs2_seq_24e.pth
[                                                  ] 0/81, elapsed: 0s, ETA:/home/chang/anaconda3/envs/streampetr/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
  File "./tools/test.py", line 262, in <module>
    main()
  File "./tools/test.py", line 232, in main
    outputs = custom_multi_gpu_test(model, data_loader, args.tmpdir,
  File "/home/chang/Desktop/Git/github/StreamPETR/projects/mmdet3d_plugin/core/apis/test.py", line 72, in custom_multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/chang/anaconda3/envs/streampetr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chang/anaconda3/envs/streampetr/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/chang/anaconda3/envs/streampetr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chang/anaconda3/envs/streampetr/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 205, in new_func
    return old_func(*args, **kwargs)
  File "/home/chang/Desktop/Git/github/StreamPETR/projects/mmdet3d_plugin/models/detectors/petr3d.py", line 218, in forward
    return self.forward_test(**data)
  File "/home/chang/Desktop/Git/github/StreamPETR/projects/mmdet3d_plugin/models/detectors/petr3d.py", line 285, in forward_test
    return self.simple_test(img_metas[0], **data)
  File "/home/chang/Desktop/Git/github/StreamPETR/projects/mmdet3d_plugin/models/detectors/petr3d.py", line 314, in simple_test
    bbox_pts = self.simple_test_pts(
  File "/home/chang/Desktop/Git/github/StreamPETR/projects/mmdet3d_plugin/models/detectors/petr3d.py", line 300, in simple_test_pts
    outs = self.pts_bbox_head(location, img_metas, topk_indexes, **data)
  File "/home/chang/anaconda3/envs/streampetr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chang/Desktop/Git/github/StreamPETR/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py", line 595, in forward
    pos_embed, cone = self.position_embeding(data, memory_center, topk_indexes, img_metas)
  File "/home/chang/Desktop/Git/github/StreamPETR/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py", line 409, in position_embeding
    img2lidars = torch.tensor(img2lidars, device=data[intrinsic].device())
KeyError: tensor([[[0.6264, 0.6264],
         [0.6284, 0.6284],
         [0.6289, 0.6289],
         ...,
         [0.3984, 0.3984],
         [0.6275, 0.6275],
         [0.6250, 0.6250]]], device='cuda:0')
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 22820) of binary: /home/chang/anaconda3/envs/streampetr/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

**Comment by changliucoding** [comment]
> @changliucoding Hi your link is not valid to me. Do you mean I changed img2lidars = data['lidar2img'].inverse() img2lidars = img2lidars.view(BN, 1, 1, 4, 4).repeat(1, H_W, D, 1, 1).view(B, LEN, D, 4, 4) img2lidars = topk_gather(img2lidars, topk_indexes) to img2lidars = np.linalg.inv(data['lidar2img'].cpu().numpy()) img2lidars = torch.tensor(img2lidars, device=data[intrinsics].device()) img2lidars = img2lidars.view(BN, 1, 1, 4, 4).repeat(1, H_W, D, 1, 1).view(B, LEN, D, 4, 4) img2lidars = topk_gather(img2lidars, topk_indexes)

I think the error happened because:
streampetr_head.py", line 409 which is : 
img2lidars = torch.tensor(img2lidars, device=data[intrinsic].device())
here we tried to get a key intrinsic from dict but it is actually a tensor.....

**Comment by exiawsh** [comment]
@changliucoding data['intrinsic']

**Comment by changliucoding** [comment]
> 

File"/home/chang/Desktop/Git/github/StreamPETR/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py", line 409, in position_embeding
    img2lidars = torch.tensor(img2lidars, device=data['intrinsic'].device())
KeyError: 'intrinsic'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 24223) of binary: /home/chang/anaconda3/envs/streampetr/bin/python

Hi, Sorry I still couldn't make it run :(

**Comment by changliucoding** [comment]
> @changliucoding data['intrinsic']

Hi! Many Thanks! it works now!
